server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: checkout-webhook
          uri: lb://payment-service
          predicates:
            - Path=/api/checkout/webhook
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=1
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/products/**,/api/categories/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/checkout
          filters:
            - StripPrefix=1
