server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
