spring:
  application:
    name: store
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5m
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}